POST http://localhost:8080/api/languages
Content-Type: application/json

{
  "code": "eng",
  "nameInEnglish": "English",
  "nameLocal": "English",
  "defaultFlagCountrycode": "GB"
}

//  "id": "643ca0a2652298daf20bba3a"
