POST http://localhost:8080/api/vocabularies
Content-Type: application/json

    {
      "language":"643ca035652298daf20bba34",
      "languageCode":"fin",
      "vocabulary": {
        "checked":{
          "notificationMessages": {
            "langRedErroraddNewLanguage":"uuden kielen lisääminen epäonnistui: ",
            "userRedIloginUserstart": "Tervetuloa",
            "userRedIloginUserend": "työn iloa!",
            "userRedEloginUserstart": "Kirjautumistiedoissa oli virhe: ",
            "userRedEloginUserend": ", yritä uudelleen",
            "userRedIlogoutstart": "Heipä hei",
            "userRedIlogoutend": "nähdään taas!",
            "usersRedEaddNewUser": "Uuden käyttäjän luominen epäonnistui: "
          },
          "welcome": {
            "WH2headlineT":"TERVETULOA TÖIHIN!",
            "WTdescribe": "Voit:\n suunnitella työpäiväsi\n suunnitella tauot\n pitää työpäiväkirjaa\n pitää tehtävien töiden listaa\n tallentaa muistiinpanoja",
            "WBloginT": "KIRJAUDU",
            "WLnewUserT": "UUSI KÄYTTÄJÄ"
          },
          "loginform": {
            "LFH2headlineT": "KIRJAUTUMINEN",
            "LFIusernameT": "käyttäjänimi",
            "LFIpasswordT": "salasana",
            "LFBsubmitT": "KIRJAUDU",
            "LFBbackT": "TAKAISIN"
          },
          "logininfo": {
            "LIBlogoutT": "KIRJAUDU ULOS"
          },
          "newuserform": {
            "NUFH2headlineT": "UUSI KÄYTTÄJÄ",
            "NUFIusernameT": "käyttäjänimi",
            "NUFInameT": "nimi",
            "NUFIpasswordT": "salasana",
            "NUFIconfirmPasswordT": "salasana uudelleen",
            "NUFBsubmitT": "TALLENNA",
            "NUFBbackT": "TAKAISIN"
          },
          "workselector": {
            "WSH1headlineT": "VALITSE: ",
            "WSSworkT": "TYÖN KOHDE:",
            "WSInewWorkT": "...TAI LISÄÄ UUSI:",
            "WSInewWorkP": "LISÄÄ UUSI TYÖ",
            "WSCisProjectT": "ON PROJEKTI",
            "WSRworkTypeT": "TYÖTAPA:",
            "WSInewWorkTypeT": "...TAI LISÄÄ UUSI:",
            "WSInewWorkTypeP": "LISÄÄ UUSI TYÖTAPA",
            "WSBsubmitT": "ALOITA TYÖT"
          }
        },
        "newPlaces": {       
          "loginform": {
            "LFIforDevT": {
              "eng": "DEV HELPER INPUT",
              "usersWhoTranslate": ["642861b1b1863882baf0ac83"],
              "translations": {
                "EKA KÄÄNNÖS INPUT": 1
              }
            },
            "LFBforDevT": {
              "eng": "DEV HELPER BUTTON",
              "usersWhoTranslate": ["642861b1b1863882baf0ac83", "642862c7b1863882baf0ac86"],
              "translations": {
                "EKA KÄÄNNÖS BUTTON": 1,
                "TOKA KÄÄNNÖS BUTTON": 1
              }
            }
          }
        }
      }
    }

 //"lastUpdate": "2023-07-07T13:15:47.230Z",
 // "id": "64a810038e031712c94c88aa"