POST http://localhost:8080/api/languages
Content-Type: application/json

{
  "code": "fin",
  "nameInEnglish": "Finnish",
  "nameLocal": "suomi",
  "defaultFlagCountrycode": "FI"
}

//  "id": "643ca035652298daf20bba34"
