POST http://localhost:8080/api/users
Content-Type: application/json

{
  "username": "englishUser",
  "name": "englishName",
  "password": "englishPassword",
  "language": "64285d05b1863882baf0ac77"
}

//  "joiningday": "2023-04-17T01:24:32.694Z",
//  "lastVisited": "2023-04-17T01:24:32.694Z",
//  "id": "643c9fd0652298daf20bba2f"
