POST http://localhost:8080/api/users
Content-Type: application/json

{
  "username": "minna",
  "name": "minnaNimi",
  "password": "salainen",
  "language": "64374b8cd5c6586018ee042f"
}

//  "joiningday": "2023-04-17T01:23:16.670Z",
//  "lastVisited": "2023-04-17T01:23:16.670Z",
//  "id": "643c9f84652298daf20bba2c"
