POST http://localhost:8080/api/vocabularies
Content-Type: application/json

    {
      "language":"643ca0a2652298daf20bba3a",
      "languageCode":"eng",
      "vocabulary": {
        "checked":{
          "notificationMessages": {
            "langRedErroraddNewLanguage":"failed to add a new language: ",
            "userRedIloginUserstart": "Welcome",
            "userRedIloginUserend": "have a good one!",
            "userRedEloginUserstart": "Failed to log in: ",
            "userRedEloginUserend": ", try again",
            "userRedIlogoutstart": "Bye bye",
            "userRedIlogoutend": "see you soon!",
            "usersRedEaddNewUser": "Failed to create a new user: "          
          },
          "welcome": {
            "WH2headlineT":"WELCOME TO WORK!",
            "WTdescribe": "You can:\n plan your work\n plan your breaks\n keep journal\n keep todo-list\n save notes",
            "WBloginT": "LOG IN",
            "WLnewUserT": "NEW USER"
          },
          "loginform": {
            "LFH2headlineT": "LOG IN",
            "LFIusernameT": "username",
            "LFIpasswordT": "password",
            "LFBsubmitT": "LOGIN",
            "LFBbackT": "BACK",
            "LFIforDevT": "DEV HELPER INPUT",
            "LFBforDevT": "DEV HELPER BUTTON"
          },
          "logininfo": {
            "LIBlogoutT": "LOG OUT"
          },
          "newuserform": {
            "NUFH2headlineT": "NEW USER",
            "NUFIusernameT": "username",
            "NUFInameT": "name",
            "NUFIpasswordT": "password",
            "NUFIconfirmPasswordT": "confirm password",
            "NUFBsubmitT": "SAVE AND LOGIN",
            "NUFBbackT": "BACK"
          },
          "workselector": {
            "WSH1headlineT": "SELECT:",
            "WSSworkT": "object of work:",
            "WSInewWorkT": "...or add a new one:",
            "WSInewWorkP": "add a new work item",
            "WSCisProjectT": "is a project",
            "WSRworkTypeT": "way of working:",
            "WSInewWorkTypeT": "...or add a new one:",
            "WSInewWorkTypeP": "add a new way of working",
            "WSBsubmitT": "start working"
          }
        }
      }
    }

//"lastUpdate": "2023-07-07T13:17:00.237Z",
//  "id": "64a8104c8e031712c94c88ad"
